### ISSUE TITLE
Quickstart environment file not working

### ISSUE THREAD

**Issue by nolan771234** [plaid/quickstart#252]
I have used the instructions provided in the readme file on this github. I am running windows, using git bash to get linux shell commands. I have installed npm and have used the core.symlinks=true to clone the github. Upon running the cp .env.example .env command i get the error "not writing through dangling symlink '.env'.  This works if i give the .env file a name such as running the command "cp .env.example test.env". However this does not work upon running the frontend server and i get "unable to fetch link_token: please make sure your backend server is running and that your .env file has been configured correctly.:. I presume you want a .env file with no name, but im not sure such thing is possible.

**Comment by nolan771234** [comment]
Update 
fixed the dangling symlink issue using the following code:
$ ln -s .env.example .env          
$ cp -f .env.example .env               
cp: not writing through dangling symlink ‘f’
$ cp --remove-destination .env.example .env
$ diff .env.example .env && echo yes
yes
cp -f .env.example .env

It worked, but when running the frontend server i still get the "unable to fetch link_token: please make sure your backend server is running and that your .env file has been configured correctly". i have an environment file in quickstart/python called .env, i put my secret and client ids in there using notepads text editor, saved it, then ran the frontend server. The backend server is running through git bash.

**Comment by nolan771234** [comment]
Update: 
noticed there was a .env.example file in /quickstart
tried the above fix in the quickstart folder rather than the quickstart/python folder
same error restarted both servers. tried deleting the files in quickstart/python 
same error
ive put the ids in the .env file
I originally started the server without the ids, and got a different error that said that i didn't put the ids in, upon putting the ids in, the error when back to the error stated above. I presume im making progress but still no success.

**Comment by nolan771234** [comment]
Update: using go has fixed the problem, however it seems this issue was related to https://github.com/plaid/quickstart/issues/246
however, this has not been fixed for python

**Comment by kevinhannonschulman** [comment]
I signed up yesterday for Quickstart and it worked perfectly while using Docker and python but today I'm receiving the same error message as above ("Unable to fetch link_token: please make sure your backend server is running and that your .env file has been configured with your PLAID_CLIENT_ID and PLAID_SECRET"). I've added the client and secret keys to my .env file and Docker appears to be working fine – am I missing something obvious?

**Comment by lindawoo-plaid** [comment]
@nolan771234, can I close this, or is there still an issue with python?

**Comment by tyliec** [comment]
I'm seeing the same issue for the NodeJS quickstart steps, is there a recommended workaround?
